Iter13
Igor-makeev/mfuss pull request #18
Opened 2023-01-01 07:28 UTC by Igor-makeev

2023-01-09 21:10 UTC, capsulated commented on internal/handler/api.go
> +			if err := utilits.CheckURL(shortURL); err != nil {
слишком много условных операторов, нужно упрощать как-то

2023-01-09 21:12 UTC, capsulated commented on internal/handler/api.go
> +	userID, err := getUserID(c)
Та же история, из `getUserID` `http writer` вытащить в хендлер надо

2023-01-09 21:21 UTC, capsulated commented on internal/handler/middleware.go
> +	isvalid := false
булевый тип и так по умолчанию `false`

префикс `is` не пишут в го, так как статическая типизация: и так видно, что это булево значение

```go
var valid bool
```

2023-01-09 21:23 UTC, capsulated commented on internal/handler/middleware.go
> +	isvalid := false
А вообще зачем эта переменная-то?

2023-01-09 21:23 UTC, capsulated commented on internal/handler/middleware.go
> +		return isvalid
```go
if err != nil {
   return false
}
```

не?

2023-01-09 21:24 UTC, capsulated commented on internal/handler/middleware.go
> +		return isvalid
ужос! 
```go
{
   return true
}
```

2023-01-09 21:25 UTC, capsulated commented on internal/handler/middleware.go
> +	return res
и тут
```go
return string(buf)
```
не?

2023-01-09 21:28 UTC, capsulated commented on internal/handler/user.go
> +		c.Status(http.StatusNoContent)
а тут статус через контекст `gin` передаётся

может везде лучше так `http` ответ возвращать? будет как-то посимпатичнее

но надо привести к единообразию

2023-01-09 21:30 UTC, capsulated commented on internal/repositories/postgresstorage.go
> +var schema = `
Эти sql-ки отдельно бы куда-нибудь перенести, а слишком громоздкие. Я обычно в init.sql скрипт создаю, но в нашем случае хотя бы в отдельный файл. Но это по-желанию. На мой взгляд нагромождает код пакета. А если их много будет?

2023-01-09 21:32 UTC, capsulated commented on internal/repositories/repository.go
>  type URLStorage interface {
`URLStorage` это имя для структуры. `URLStorager` для интерфейса. При использовании путаница будет

2023-01-09 21:36 UTC, capsulated commented on internal/repositories/repository.go
>  type URLStorage interface {
Что-то многовато интерфейсов. Видимо, не совсем ясна идея использования интерфейсов. 

Один интерфейс для хранилки и несколько разных реализаций должно быть: `file`, `memory`, `db`

Сейчас есть некоторый беспорядок. Нужно привести  к одному интерфейсу

2023-01-10 01:07 UTC, Igor-makeev commented on internal/handler/api.go
> +		return
Сделано

2023-01-10 01:10 UTC, Igor-makeev commented on internal/handler/api.go
> +
Сделано

2023-01-10 01:25 UTC, Igor-makeev commented on internal/handler/api.go
> +	switch {
Сделано

2023-01-10 01:26 UTC, Igor-makeev commented on internal/handler/api.go
> +			if err := utilits.CheckURL(shortURL); err != nil {
Вроде  сделал по другому но всё равно терзают смутные сомнения

2023-01-10 01:26 UTC, Igor-makeev commented on internal/handler/api.go
> +	userID, err := getUserID(c)
Сделано

2023-01-10 01:45 UTC, Igor-makeev commented on internal/handler/api.go
> +	for _, v := range input {
Сделано

2023-01-10 01:47 UTC, Igor-makeev commented on internal/handler/middleware.go
> +	isvalid := false
Сделано

2023-01-10 02:35 UTC, Igor-makeev commented on internal/handler/user.go
> +		c.Status(http.StatusNoContent)
Сделано

2023-01-10 02:42 UTC, Igor-makeev commented on internal/repositories/postgresstorage.go
> +var schema = `
Сделано

2023-01-10 02:46 UTC, Igor-makeev commented on internal/repositories/repository.go
>  type URLStorage interface {
Интерфейс для хранилки с двумя реализациями memory и db  А уже у memory в составе структуры есть интерфейс PersistentStorage, которы при случае вместо файла можно подменить бд или ещё чем нибудь, основная задумка такая)

2023-01-12 02:10 UTC, capsulated requested changes
Всё вроде поправил, а автотест на 2 инкременте упал?

Насчёт интерфейсов и структуры объектов можно 1-1 взять - расскажу идею. В нашем случае два интерфейса - усложнение, которого можно избежать

2023-01-12 05:50 UTC, Igor-makeev commented
> Всё вроде поправил, а автотест на 2 инкременте упал?
> 
> Насчёт интерфейсов и структуры объектов можно 1-1 взять - расскажу идею. В нашем случае два интерфейса - усложнение, которого можно избежать

Автотест переодически падает, из за того что я там горутину использую, лечится рераном джобов. Я уже придумал как это поправить. Идею готов выслушать в любое удобное время)

2023-01-13 16:20 UTC, capsulated approved these changes
Всё супер! 

Обсудили всё на 1-1

2023-01-13 16:22 UTC, merged