Iter14
Igor-makeev/mfuss pull request #20
Opened 2023-01-24 07:09 UTC by Igor-makeev

2023-01-27 13:25 UTC, bambruysk requested changes
Самая грубая ошибка - конексты . Нужно исправить.

2023-01-27 14:27 UTC, Igor-makeev commented on cmd/shortener/main.go
> +	go queu.Listen(ctx, rep.MarkAsDeleted, rep.Queue.UpdateInterval)
Сделано

2023-01-27 14:28 UTC, Igor-makeev commented on internal/entity/entity.go
> +	IsDelited bool   `json:"-"`
Исправленно

2023-01-27 14:29 UTC, Igor-makeev commented on internal/handler/api.go
> +func (h *Handler) GetUSERURLS(c *gin.Context) {
Исправленно

2023-01-27 14:57 UTC, Igor-makeev commented on internal/repositories/postgresstorage.go
> +	conn, err := pgx.Connect(context.Background(), cfg.DBDSN)
Сделано

2023-01-27 15:00 UTC, Igor-makeev commented on internal/repositories/postgresstorage.go
>  	ps.Lock()
Исправил

2023-01-27 15:24 UTC, Igor-makeev commented on internal/repositories/postgresstorage.go
> +	if err := ps.DB.QueryRow(context.Background(), `select id,result,origin,user_id, Is_deleted from url_store where id=$1 ;`, id).Scan(&url.ID, &url.ResultURL, &url.Origin, &url.UserID, &url.IsDelited)
Сделано

2023-01-27 15:34 UTC, Igor-makeev commented on internal/repositories/queue.go
> +			if len(q.Buf) == cap(q.Buf) {
Исправил

2023-01-27 15:44 UTC, Igor-makeev commented on internal/repositories/queue.go
> +	sync.Mutex
исправил

2023-01-27 16:52 UTC, Igor-makeev commented on cmd/shortener/main.go
> +	queu := repositories.NewQueue()
На этот счёт мнения у менторов рознятся, поэтому, если это не критично, то оставлю как есть)

2023-01-27 18:04 UTC, Igor-makeev commented on internal/repositories/queue.go
> +type Queue struct {
Исправил

2023-01-27 18:21 UTC, Igor-makeev commented on internal/repositories/queue.go
> +				commitData(q.Buf)
Сделано.

2023-01-27 18:22 UTC, Igor-makeev commented on internal/handler/api.go
> +	h.Repo.Queue.Write(inputArray)
Сделаною

2023-01-27 18:24 UTC, Igor-makeev commented on internal/mock/mock.go
>  type StorageMock struct {
Ранее ментор не акцентировал на этом внимания и я не до конца понимаю как генерируемые моки прикрутить к тому что есть, но думаю рукотворные заглушки не являются критичной ошибкой.

2023-01-29 15:14 UTC, bambruysk commented on cmd/shortener/main.go
> +	queu := repositories.NewQueue()
Репозиторий - как раз про выбор нужного типа хранилища - это его зона отвественности.

2023-01-29 15:15 UTC, bambruysk commented on internal/mock/mock.go
>  type StorageMock struct {
нет, не является ошибкой. Это совет на будущее, потому что писать в ручную их на практике - непрактично.

2023-01-29 15:19 UTC, Igor-makeev commented on cmd/shortener/main.go
> +	queu := repositories.NewQueue()
Исправил

2023-01-29 15:20 UTC, Igor-makeev commented on internal/mock/mock.go
>  type StorageMock struct {
Понял, учту, глубже разберусь в теме

2023-01-29 15:43 UTC, bambruysk approved these changes
Контексты поправить еще чуть чуть и ок.

Остальные советы по возможности.

2023-01-29 15:43 UTC, bambruysk commented on internal/repositories/postgresstorage.go
> +func (ps *PostgresStorage) GetAllURLs(userID string, ctx context.Context) []entity.ShortURL {
https://pkg.go.dev/context 

Как указано в документации - The Context should be the first parameter, typically named ctx.

Лучше сразу привыкнуть к этому стилю

2023-01-29 15:43 UTC, bambruysk commented on internal/repositories/postgresstorage.go
> +	_, err := ps.DB.Exec(context.Background(), "UPDATE url_store SET Is_deleted = true WHERE ID = ANY ($1) and is_deleted <> true", arr)
Здесь тоже должен быть внешний контекст

2023-01-29 15:43 UTC, bambruysk commented on internal/service/queue.go
> +			commitDataFunc(q.Buf)
Два раза получается вызывается? Зачем сюда это замыкаение пробрасывается?  

выглядит не гошно) если есть время и настроение лучше вот так сделать 

 Queue struct -  сюда добавляем переменную интерфейсного типа Committer - с названием типа store - 
 При создании очереди в нее записываем указатель на репозиторий который реализует этот метод.
 Пользуемся этим методом
 Готово!
 
 Плюсы - не нужно пробрасывать лишние функции.
 
 Код более чистый, так как вызывающая сторона ничего не знает о коммитах

2023-01-29 15:43 UTC, bambruysk commented on internal/service/urlstorage.go
> +	repo repositories.URLStorager
Для обеспечения чистой архитектуры  мы здесь объвялем локально интерфейс который требует нам похожие методы из репозитория - похожий на копию epositories.URLStorager 

Он должен быть его подмножеством. 

Тогда можно его успешно замокать тут и протестировать бизнес-логику независимо от слоя репозитория

2023-01-29 15:43 UTC, bambruysk commented on internal/service/urlstorage.go
> +
Например, генерация короткой ссылки - это теперь явно часть этого метода. Если у нас меняется алгоритм, то его изменения отражаются разве что здесь, но не в хенжделрах или слое хранения

2023-01-29 16:04 UTC, Igor-makeev commented on internal/repositories/postgresstorage.go
> +func (ps *PostgresStorage) GetAllURLs(userID string, ctx context.Context) []entity.ShortURL {
Исправил

2023-01-29 16:04 UTC, Igor-makeev commented on internal/repositories/postgresstorage.go
> +	_, err := ps.DB.Exec(context.Background(), "UPDATE url_store SET Is_deleted = true WHERE ID = ANY ($1) and is_deleted <> true", arr)
Исправил

2023-01-29 16:44 UTC, Igor-makeev commented on internal/service/urlstorage.go
> +	repo repositories.URLStorager
Я могу ошибаться, но локальный интерфейс объявлен в файле service.go или это не то ?

2023-01-29 17:18 UTC, merged